export const LOAD_NEARBY_RESTAURANTS = 'LOAD_NEARBY_RESTAURANTS';
export const LOAD_NEARBY_RESTAURANTS_SUCCESS = 'LOAD_NEARBY_RESTAURANTS_SUCCESS';
export const LOAD_NEARBY_RESTAURANTS_ERROR = 'LOAD_NEARBY_RESTAURANTS_ERROR';

export const LOAD_RESTAURANT = 'LOAD_RESTAURANT';
export const LOAD_RESTAURANT_SUCCESS = 'LOAD_RESTAURANT_SUCCESS';
export const LOAD_RESTAURANT_ERROR = 'LOAD_RESTAURANT_ERROR';
